---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjYmIwNjA5My1rcjEtcmVnaXN0cnkuY29udGFpbmVyLmNsb3VkLnRvYXN0LmNvbSI6IHsKCQkJImF1dGgiOiAiYVc1bWJ6RXdNRUJwYm1wbGFXNWpMbU52TG10eU9rUmtNV0ptWkZadldFSk5OSGRSVVV3PSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: nhn-registry-auth
  namespace: soob
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: soob-app
  name: soob-app
  namespace: soob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soob-app
  template:
    metadata:
      labels:
        app: soob-app
    spec:
      imagePullSecrets:
      -
        name: nhn-registry-auth
      containers:
      -
        image: 'cbb06093-kr1-registry.container.cloud.toast.com/tomcat8-soob:latest'
        name: soob-app
        ports:
        -
          containerPort: 8080
          name: soob-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: soob-app
  name: test-soob-service
  namespace: soob
spec:
  ports:
  -
    name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: soob-app
  type: LoadBalancer
